name: Update Google Slides Menu

on:
  workflow_dispatch:
schedule:
    - cron: '0 7 1 * *'
jobs:
  update_slide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set CLIENT_SECRETS_JSON inline
    - name: Set CLIENT_SECRETS_JSON
      run: |
        echo "CLIENT_SECRETS_JSON<<EOF" >> $GITHUB_ENV
        cat <<EOF >> $GITHUB_ENV

EOF

    - name: Run menu updater
      run: python dinnermenu.py | python slides.py
